labels:
  - name: 'Priority: Low'
    color: 009800
  - name: 'Priority: Medium'
    color: fbca04
  - name: 'Priority: High'
    color: eb6420
  - name: 'Priority: Critical'
    color: e11d21
  - name: 'Status: Abandoned'
    color: 000000
  - name: 'Status: Accepted'
    color: 009800
  - name: 'Status: Available'
    color: bfe5bf
  - name: 'Status: Planned'
    color: 30336b
  - name: 'Status: Blocked'
    color: e11d21
  - name: 'Status: Completed'
    color: 006b75
  - name: 'Status: In Progress'
    color: cccccc
  - name: 'Status: On Hold'
    color: e11d21
  - name: 'Status: Pending'
    color: fef2c0
  - name: 'Status: Reviewed'
    color: 6ab04c
  - name: 'Status: Review Needed'
    color: fbca04
  - name: 'Status: Revision Needed'
    color: e11d21
  - name: 'Type: Bug'
    color: e11d21
  - name: 'Type: Maintenance'
    color: fbca04
  - name: 'Type: Idea'
    color: 009432
  - name: 'Type: Enhancement'
    color: 84b6eb
  - name: 'Type: Question'
    color: cc317c
  - name: good first issue
    color: 22a6b3